# Creating Arrays

In [34]:
import numpy as np

In [35]:
np.zeros

<function numpy.zeros>

The ```zeros``` function creates an array containing any number of zeros:

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

2D array

In [37]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

* Each dimension is called an axis.
* The number of axes is called the rank.
    * the above matrix is an array of rank 2(2D)
    * the first axis has length 3, the second has length 4.
* an array's list of axis lengths is called the shape of the array.
    * the above's matrix's shape is (3, 4).
    * the rank is equal to the shape's length.
* The size of an array is the total number of elements, which is the product of all axis lengths (3*4=12) 

In [38]:
a = np.zeros((3,4))
a
a.shape

(3, 4)

In [39]:
a.ndim # equal to len(a.shape)

2

In [40]:
a.size

12

## N-dimensional arrays
rank=3 shape =(2,3,4)

In [41]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Array type
NumPy arrays hace the type ndarray s:

In [42]:
type(np.zeros((3,4)))

numpy.ndarray

### ```np.ones```
Many other NumPy functions create ```ndarray```s.
3x4 matrix full of ones:

In [43]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

```np.full```
Creates an array of the given shape initialized with the given value.

In [44]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

```np.empty```
An unitialized 2x3 array(its content is not predictable, as it is whatever is in memory at that point):

In [45]:
np.empty((2,3))

array([[-3.10503618e+231,  2.00389992e+000,  6.07844469e-067],
       [ 1.56111118e+161,  6.01180714e-067,  4.17201348e-309]])

```np.array```
you can initialize an ```ndarray``` using a regular python array.

In [ ]:
np.array([[1,2,3,4], [10,20,30,40]])