# Creating Arrays

In [13]:
import numpy as np

In [14]:
np.zeros

<function numpy.zeros>

The ```zeros``` function creates an array containing any number of zeros:

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

2D array

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

* Each dimension is called an axis.
* The number of axes is called the rank.
    * the above matrix is an array of rank 2(2D)
    * the first axis has length 3, the second has length 4.
* an array's list of axis lengths is called the shape of the array.
    * the above's matrix's shape is (3, 4).
    * the rank is equal to the shape's length.
* The size of an array is the total number of elements, which is the product of all axis lengths (3*4=12) 

In [17]:
a = np.zeros((3,4))
a
a.shape

(3, 4)

In [18]:
a.ndim # equal to len(a.shape)

2

In [19]:
a.size

12

## N-dimensional arrays
rank=3 shape =(2,3,4)

In [20]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Array type
NumPy arrays hace the type ndarray s:

In [21]:
type(np.zeros((3,4)))

numpy.ndarray

## ```np.ones```
Many other NumPy functions create ```ndarray```s.
3x4 matrix full of ones:

In [22]:
np.ones((3,4))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])